const { canAccessModule, normalizeRole } = require('../../config/rbac');

const MODULES = [
  {
    key: 'painel',
    title: 'Painel Principal',
    icon: '▦',
    category: 'Operação',
    permission: 'painel_operacional',
    href: '/dashboard',
    summary: 'Visão rápida da operação da manutenção, indicadores, alertas e situação das atividades.',
    actions: [
      ['painel_operacional', 'Acompanhar indicadores e situação operacional'],
      ['dashboard_criticidade', 'Consultar criticidade e prioridades do setor'],
    ],
  },
  {
    key: 'diretoria-manutencao',
    title: 'Desempenho da Manutenção',
    icon: '◫',
    category: 'Gestão',
    permission: 'diretoria_manutencao',
    href: '/dashboard/diretoria/manutencao',
    summary: 'Painel executivo com desempenho, custos, disponibilidade e indicadores gerenciais da manutenção.',
    actions: [
      ['diretoria_manutencao', 'Consultar indicadores executivos da manutenção'],
    ],
  },
  {
    key: 'diretoria-compras',
    title: 'Acompanhamento de Compras',
    icon: '◫',
    category: 'Gestão',
    permission: 'diretoria_compras',
    href: '/dashboard/diretoria/compras',
    summary: 'Acompanhamento gerencial das solicitações e compras sem substituir a operação do setor de Compras.',
    actions: [
      ['diretoria_compras', 'Acompanhar solicitações, andamento e situação das compras'],
    ],
  },
  {
    key: 'equipamentos',
    title: 'Equipamentos',
    icon: '⚙',
    category: 'Manutenção',
    permission: 'equipamentos',
    href: '/equipamentos',
    summary: 'Cadastro técnico dos ativos, identificação, histórico, peças e informações utilizadas pela manutenção.',
    actions: [
      ['equipamentos', 'Consultar equipamentos e histórico'],
      ['equipamentos_manage', 'Cadastrar e atualizar dados técnicos'],
      ['equipamentos_delete', 'Excluir registros quando permitido'],
    ],
  },
  {
    key: 'os',
    title: 'Ordens de Serviço',
    icon: '✓',
    category: 'Manutenção',
    permission: 'os_view',
    href: '/os',
    summary: 'Fluxo principal para registrar, planejar, executar e fechar serviços de manutenção.',
    actions: [
      ['os_view', 'Consultar ordens de serviço'],
      ['os_open', 'Abrir novas ordens de serviço'],
      ['os_execute', 'Executar, registrar andamento e fechar serviços'],
      ['os_delete', 'Excluir ordens quando permitido'],
    ],
  },
  {
    key: 'chat-os',
    title: 'Chat de OS',
    icon: '◌',
    category: 'Manutenção',
    permission: 'os_chat_read',
    href: '/chat-os',
    summary: 'Comunicação vinculada às ordens de serviço, mantendo conversas e registros no contexto da atividade.',
    actions: [
      ['os_chat_read', 'Ler conversas das OS autorizadas'],
      ['os_chat_write', 'Enviar mensagens e atualizações'],
      ['os_chat_manage', 'Gerenciar conversas quando permitido'],
    ],
  },
  {
    key: 'preventivas',
    title: 'Preventivas',
    icon: '◷',
    category: 'Manutenção',
    permission: 'preventivas_view',
    href: '/preventivas',
    summary: 'Execução e acompanhamento das atividades preventivas programadas para os equipamentos.',
    actions: [
      ['preventivas_view', 'Consultar programação preventiva'],
      ['preventivas_execute', 'Executar e dar baixa nas preventivas'],
      ['preventivas_manage', 'Configurar e programar planos preventivos'],
    ],
  },
  {
    key: 'lubrificacao',
    title: 'Roteiro de Lubrificação',
    icon: '◉',
    category: 'Manutenção',
    permission: 'lubrificacao_execucao',
    href: '/lubrificacao',
    summary: 'Roteiro operacional de lubrificação com pontos, periodicidades e registro de execução.',
    actions: [
      ['lubrificacao_execucao', 'Executar e registrar o roteiro distribuído'],
    ],
  },
  {
    key: 'demandas',
    title: 'Demandas',
    icon: '☷',
    category: 'Planejamento',
    permission: 'demandas_view',
    href: '/demandas',
    summary: 'Banco de necessidades da manutenção, priorização, materiais, planejamento e conversão para execução.',
    actions: [
      ['demandas_view', 'Consultar demandas'],
      ['demandas_open', 'Abrir novas demandas'],
      ['demandas_manage', 'Planejar, organizar e atualizar demandas'],
      ['demandas_materials', 'Trabalhar materiais e pré-cotação'],
      ['demandas_approve', 'Aprovar e priorizar quando autorizado'],
      ['demandas_convert', 'Converter demanda aprovada em OS'],
    ],
  },
  {
    key: 'solicitacoes',
    title: 'Solicitações',
    icon: '☷',
    category: 'Materiais e Compras',
    permission: 'solicitacoes_read',
    href: '/solicitacoes/minhas',
    summary: 'Solicitação de materiais e serviços com acompanhamento do fluxo até compras, recebimento e entrega.',
    actions: [
      ['solicitacoes_read', 'Consultar solicitações autorizadas'],
      ['solicitacoes_create', 'Criar solicitações'],
      ['solicitacoes_manage', 'Editar e acompanhar solicitações do setor'],
    ],
  },
  {
    key: 'acompanhamento-compras',
    title: 'Acompanhamento de Compras',
    icon: '⌕',
    category: 'Materiais e Compras',
    permission: 'acompanhamento_compras',
    href: '/acompanhamento-compras',
    summary: 'Consulta gerencial do andamento das compras do setor, sem liberar as ações operacionais do Compras.',
    actions: [
      ['acompanhamento_compras', 'Acompanhar o andamento das compras do setor'],
    ],
  },
  {
    key: 'pre-solicitacoes',
    title: 'Pré-Solicitações',
    icon: '＋',
    category: 'Materiais e Compras',
    permission: 'pre_solicitacao_almox_read',
    href: '/pre-solicitacoes',
    summary: 'Preparação antecipada de materiais antes da solicitação formal, com separação das responsabilidades do Almoxarifado e setor.',
    actions: [
      ['pre_solicitacao_almox_read', 'Consultar pré-solicitações'],
      ['pre_solicitacao_almox_create', 'Criar pré-solicitações'],
      ['pre_solicitacao_setor_approve', 'Aprovar pelo setor responsável'],
    ],
  },
  {
    key: 'compras',
    title: 'Compras',
    icon: '◇',
    category: 'Materiais e Compras',
    permission: 'compras',
    href: '/compras/solicitacoes',
    summary: 'Operação do setor de Compras: cotações, fornecedores, pedidos e acompanhamento dos itens adquiridos.',
    actions: [
      ['compras', 'Acessar a operação de Compras'],
      ['compras_manage', 'Cotação, compra e atualização do processo'],
    ],
  },
  {
    key: 'fornecedores',
    title: 'Fornecedores',
    icon: '♙',
    category: 'Materiais e Compras',
    permission: 'fornecedores',
    href: '/fornecedores',
    summary: 'Base de fornecedores utilizados em compras, serviços e cotações.',
    actions: [
      ['fornecedores', 'Consultar fornecedores'],
      ['fornecedores_manage', 'Cadastrar e atualizar fornecedores'],
    ],
  },
  {
    key: 'almoxarifado',
    title: 'Almoxarifado',
    icon: '▣',
    category: 'Materiais e Compras',
    permission: 'almoxarifado_read',
    href: '/almoxarifado/recebimentos',
    summary: 'Recebimento, conferência, armazenamento e entrega física dos materiais ligados ao estoque.',
    actions: [
      ['almoxarifado_read', 'Consultar recebimentos e materiais'],
      ['almoxarifado_manage', 'Receber, conferir e entregar materiais'],
    ],
  },
  {
    key: 'estoque',
    title: 'Estoque',
    icon: '▤',
    category: 'Materiais e Compras',
    permission: 'estoque_view',
    href: '/estoque',
    summary: 'Controle de saldo, entradas, saídas, localização e rastreabilidade dos materiais armazenados.',
    actions: [
      ['estoque_view', 'Consultar itens e saldos'],
      ['estoque_manage', 'Gerenciar cadastro e movimentações'],
      ['estoque_retirada', 'Registrar retirada quando autorizado'],
    ],
  },
  {
    key: 'motores',
    title: 'Motores',
    icon: '⚙',
    category: 'Manutenção',
    permission: 'motores',
    href: '/motores',
    summary: 'Controle de motores industriais, situação, identificação e histórico de manutenção ou rebobinamento.',
    actions: [
      ['motores', 'Consultar e acompanhar motores'],
    ],
  },
  {
    key: 'avisos',
    title: 'Avisos',
    icon: '!',
    category: 'Gestão e Apoio',
    permission: 'avisos_view',
    href: '/avisos',
    summary: 'Comunicação interna do sistema para avisos operacionais e informações relevantes às equipes.',
    actions: [
      ['avisos_view', 'Consultar avisos'],
      ['avisos_manage', 'Publicar e gerenciar avisos'],
    ],
  },
  {
    key: 'escala',
    title: 'Escala e Jornada',
    icon: '◷',
    category: 'Pessoas',
    permission: 'escala',
    href: '/escala',
    summary: 'Escalas, horas extras, folgas, banco de horas e acompanhamento da jornada da equipe.',
    actions: [
      ['escala', 'Consultar escala geral quando autorizado'],
      ['escala_self', 'Consultar o próprio painel de jornada'],
      ['escala_manage', 'Gerenciar escala e apontamentos'],
      ['escala_reports', 'Emitir relatórios autorizados'],
    ],
  },
  {
    key: 'rh',
    title: 'RH',
    icon: '♙',
    category: 'Pessoas',
    permission: 'rh_view',
    href: '/rh',
    summary: 'Gestão de pessoas, exames, documentos e informações administrativas conforme o perfil do usuário.',
    actions: [
      ['rh_view', 'Consultar informações de RH autorizadas'],
      ['rh_manage', 'Gerenciar cadastros e rotinas do RH'],
      ['rh_sensitive', 'Acessar dados sensíveis quando autorizado'],
    ],
  },
  {
    key: 'meu-portal',
    title: 'Meu Portal',
    icon: '●',
    category: 'Pessoal',
    always: true,
    href: '/meu-portal',
    summary: 'Área pessoal do usuário com identidade, cartão do Almoxarifado, jornada, RH, conta e serviços de autoatendimento disponíveis.',
    actions: [
      [null, 'Consultar informações e serviços pessoais liberados para o usuário'],
    ],
  },
  {
    key: 'inspecao',
    title: 'Inspeção',
    icon: '✓',
    category: 'Qualidade',
    permission: 'inspecao_view',
    href: '/inspecao',
    summary: 'Registro e acompanhamento de inspeções e não conformidades ligadas aos ativos e processos.',
    actions: [
      ['inspecao_view', 'Consultar inspeções'],
      ['inspecao_edit', 'Registrar e atualizar inspeções'],
    ],
  },
  {
    key: 'tracagem',
    title: 'Traçagem',
    icon: '⌁',
    category: 'Engenharia',
    permission: 'tracagem_view',
    href: '/tracagem',
    summary: 'Ferramentas de cálculo e desenvolvimento para peças, chapas, curvas, transições e projetos de fabricação.',
    actions: [
      ['tracagem_view', 'Usar calculadoras e consultar projetos'],
      ['tracagem_manage', 'Gerenciar projetos e vínculos'],
    ],
  },
  {
    key: 'desenho-tecnico',
    title: 'Desenho Técnico',
    icon: '⌑',
    category: 'Engenharia',
    permission: 'desenho_tecnico_view',
    href: '/desenho-tecnico',
    summary: 'Editor CAD técnico para desenhos mecânicos, cotas, vistas, arquivos e documentação de fabricação.',
    actions: [
      ['desenho_tecnico_view', 'Abrir e consultar desenhos'],
      ['desenho_tecnico_manage', 'Criar, editar e salvar desenhos'],
    ],
  },
  {
    key: 'academia',
    title: 'Academia da Manutenção',
    icon: '☆',
    category: 'Conhecimento',
    permission: 'academia_view',
    href: '/academia',
    summary: 'Conteúdo técnico e treinamento interno para desenvolvimento da equipe de manutenção.',
    actions: [
      ['academia_view', 'Acessar conteúdos e treinamentos'],
      ['academia_manage', 'Gerenciar materiais de treinamento'],
    ],
  },
  {
    key: 'assistente',
    title: 'Assistente da Manutenção',
    icon: '✦',
    category: 'Conhecimento',
    permission: 'assistente_manutencao',
    href: '/ai/chat',
    summary: 'Assistente industrial para consulta técnica, apoio ao diagnóstico e uso contextual dos dados autorizados.',
    actions: [
      ['assistente_manutencao', 'Utilizar o assistente conforme o perfil'],
    ],
  },
  {
    key: 'pcm',
    title: 'PCM – Planejamento',
    icon: '▥',
    category: 'Planejamento',
    permission: 'pcm',
    href: '/pcm',
    summary: 'Área técnica de planejamento e controle da manutenção: plano mestre, programação, lubrificação, criticidade, falhas e indicadores.',
    actions: [
      ['pcm', 'Acessar o PCM operacional'],
      ['pcm_manage', 'Gerenciar planejamento e parâmetros do PCM'],
    ],
  },
  {
    key: 'modo-tv',
    title: 'Modo TV',
    icon: '▣',
    category: 'Gestão e Apoio',
    always: true,
    href: '/tv',
    summary: 'Painel de exibição contínua para TV com informações operacionais e acompanhamento visual do setor.',
    actions: [
      [null, 'Abrir a visualização do Modo TV'],
    ],
  },
  {
    key: 'saude-sistema',
    title: 'Saúde do Sistema',
    icon: '♥',
    category: 'Sistema',
    roles: ['ADMIN', 'ENCARREGADO_MANUTENCAO', 'MANUTENCAO_SUPERVISOR', 'SUPERVISOR_MANUTENCAO'],
    href: '/admin/armazenamento',
    summary: 'Diagnóstico de armazenamento e rotinas administrativas para manter o volume do sistema saudável.',
    actions: [
      [null, 'Consultar armazenamento e executar rotinas administrativas autorizadas'],
    ],
  },
  {
    key: 'usuarios',
    title: 'Gerenciar Usuários',
    icon: '♙',
    category: 'Sistema',
    permission: 'usuarios',
    href: '/usuarios',
    summary: 'Administração de usuários, perfis e acessos do sistema.',
    actions: [
      ['usuarios', 'Gerenciar usuários e perfis'],
    ],
  },
];

function getGuideForRole(role) {
  const normalizedRole = normalizeRole(role);
  return MODULES
    .filter((module) => module.always
      || (Array.isArray(module.roles) && module.roles.map(normalizeRole).includes(normalizedRole))
      || canAccessModule(normalizedRole, module.permission))
    .map((module) => ({
      ...module,
      actions: module.actions
        .filter(([permission]) => !permission || canAccessModule(normalizedRole, permission))
        .map(([, label]) => label),
    }));
}

module.exports = {
  getGuideForRole,
};
