const ROLE = {
  ADMIN: 'ADMIN',
  DIRETORIA: 'DIRETORIA',
  RH: 'RH',
  ENCARREGADO_PRODUCAO: 'ENCARREGADO_PRODUCAO',
  PRODUCAO: 'PRODUCAO',
  MECANICO: 'MECANICO',
  ALMOXARIFADO: 'ALMOXARIFADO',
  COMPRAS: 'COMPRAS',
  MANUTENCAO_SUPERVISOR: 'MANUTENCAO_SUPERVISOR',
  SUPERVISOR_MANUTENCAO: 'SUPERVISOR_MANUTENCAO',
  ENCARREGADO_MANUTENCAO: 'ENCARREGADO_MANUTENCAO',
  GESTAO: 'GESTAO',
  COLABORADOR: 'COLABORADOR',
  INSPECAO_QUALIDADE: 'INSPECAO_QUALIDADE',
};

function normalizeRole(role) {
  const r = String(role || '')
    .trim()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toUpperCase()
    .replace(/[\s-]+/g, '_');
  if (r === 'ADMINISTRADOR') return ROLE.ADMIN;
  if (r === 'DIRECAO') return ROLE.DIRETORIA;
  if (r === 'ALMOXARIFE') return ROLE.ALMOXARIFADO;
  if (r === 'MANUTENCAO') return ROLE.MANUTENCAO_SUPERVISOR;
  if (r === 'SUPERVISOR_MANUTENCAO') return ROLE.MANUTENCAO_SUPERVISOR;
  if (['ENCARREGADO', 'ENCARREGADO_MANUTENCAO', 'ENCARREGADO_DE_MANUTENCAO'].includes(r)) return ROLE.ENCARREGADO_MANUTENCAO;
  if (['INSPECAO_QUALIDADE', 'INSPECAO_E_QUALIDADE', 'QUALIDADE'].includes(r)) return ROLE.INSPECAO_QUALIDADE;
  return r;
}

const ACCESS = {
  painel_operacional: [ROLE.INSPECAO_QUALIDADE, ROLE.ADMIN, ROLE.DIRETORIA, ROLE.RH, ROLE.ENCARREGADO_PRODUCAO, ROLE.PRODUCAO, ROLE.MECANICO, ROLE.MANUTENCAO_SUPERVISOR],
  pcm: [ROLE.ADMIN, ROLE.MANUTENCAO_SUPERVISOR],
  equipamentos: [ROLE.INSPECAO_QUALIDADE, ROLE.ADMIN, ROLE.MECANICO, ROLE.MANUTENCAO_SUPERVISOR],
  os_view: [ROLE.INSPECAO_QUALIDADE, ROLE.ADMIN, ROLE.DIRETORIA, ROLE.RH, ROLE.ENCARREGADO_PRODUCAO, ROLE.PRODUCAO, ROLE.MECANICO, ROLE.MANUTENCAO_SUPERVISOR],
  os_open: [ROLE.INSPECAO_QUALIDADE, ROLE.ADMIN, ROLE.DIRETORIA, ROLE.ENCARREGADO_PRODUCAO, ROLE.PRODUCAO, ROLE.MECANICO, ROLE.MANUTENCAO_SUPERVISOR],
  os_execute: [ROLE.ADMIN, ROLE.MECANICO, ROLE.MANUTENCAO_SUPERVISOR],
  os_chat_read: [ROLE.ADMIN, ROLE.MANUTENCAO_SUPERVISOR, ROLE.ENCARREGADO_MANUTENCAO, ROLE.MECANICO, ROLE.COMPRAS, ROLE.INSPECAO_QUALIDADE, ROLE.DIRETORIA, ROLE.ALMOXARIFADO],
  os_chat_write: [ROLE.ADMIN, ROLE.MANUTENCAO_SUPERVISOR, ROLE.ENCARREGADO_MANUTENCAO, ROLE.MECANICO, ROLE.COMPRAS, ROLE.INSPECAO_QUALIDADE, ROLE.ALMOXARIFADO],
  os_chat_manage: [ROLE.ADMIN, ROLE.MANUTENCAO_SUPERVISOR, ROLE.ENCARREGADO_MANUTENCAO],
  // Regra operacional: quem acessa o painel operacional também enxerga Preventivas.
  preventivas_view: [ROLE.INSPECAO_QUALIDADE, ROLE.ADMIN, ROLE.DIRETORIA, ROLE.RH, ROLE.ENCARREGADO_PRODUCAO, ROLE.MECANICO, ROLE.MANUTENCAO_SUPERVISOR],
  preventivas_manage: [ROLE.ADMIN, ROLE.MANUTENCAO_SUPERVISOR, ROLE.ENCARREGADO_MANUTENCAO],
  demandas_view: [ROLE.INSPECAO_QUALIDADE, ROLE.ADMIN, ROLE.DIRETORIA, ROLE.RH],
  demandas_open: [ROLE.INSPECAO_QUALIDADE, ROLE.ADMIN, ROLE.DIRETORIA],
  demandas_manage: [ROLE.ADMIN],

  compras_read: [ROLE.ADMIN, ROLE.COMPRAS, ROLE.DIRETORIA, ROLE.GESTAO],
  compras_manage: [ROLE.ADMIN, ROLE.COMPRAS],
  solicitacoes_read: [ROLE.INSPECAO_QUALIDADE, ROLE.ADMIN, ROLE.DIRETORIA, ROLE.COMPRAS, ROLE.ALMOXARIFADO, ROLE.ENCARREGADO_PRODUCAO, ROLE.ENCARREGADO_MANUTENCAO, ROLE.MANUTENCAO_SUPERVISOR],
  solicitacoes_create: [ROLE.INSPECAO_QUALIDADE, ROLE.ADMIN, ROLE.ENCARREGADO_PRODUCAO, ROLE.ENCARREGADO_MANUTENCAO, ROLE.MANUTENCAO_SUPERVISOR, ROLE.DIRETORIA],
  solicitacoes_manage: [ROLE.ADMIN, ROLE.ENCARREGADO_MANUTENCAO, ROLE.MANUTENCAO_SUPERVISOR],
  almoxarifado_read: [ROLE.ADMIN, ROLE.ALMOXARIFADO, ROLE.COMPRAS, ROLE.DIRETORIA],
  almoxarifado_manage: [ROLE.ADMIN, ROLE.ALMOXARIFADO],
  diretoria_aprovacao: [ROLE.ADMIN, ROLE.DIRETORIA, ROLE.GESTAO],
  notificacoes_view: [ROLE.INSPECAO_QUALIDADE, ROLE.ADMIN, ROLE.DIRETORIA, ROLE.COMPRAS, ROLE.ALMOXARIFADO, ROLE.ENCARREGADO_PRODUCAO, ROLE.ENCARREGADO_MANUTENCAO, ROLE.MANUTENCAO_SUPERVISOR],
  avisos_view: [ROLE.ADMIN, ROLE.DIRETORIA, ROLE.RH, ROLE.ENCARREGADO_PRODUCAO, ROLE.MANUTENCAO_SUPERVISOR],
  avisos_manage: [ROLE.ADMIN, ROLE.DIRETORIA, ROLE.RH, ROLE.ENCARREGADO_PRODUCAO, ROLE.MANUTENCAO_SUPERVISOR],
  estoque_manage: [ROLE.ADMIN, ROLE.ALMOXARIFADO],
  estoque_view: [ROLE.ADMIN, ROLE.ALMOXARIFADO, ROLE.COMPRAS],
  motores: [ROLE.ADMIN, ROLE.ALMOXARIFADO, ROLE.MANUTENCAO_SUPERVISOR],
  compras: [ROLE.ADMIN, ROLE.COMPRAS],
  fornecedores: [ROLE.ADMIN, ROLE.COMPRAS, ROLE.GESTAO],
  usuarios: [ROLE.ADMIN],
  escala: [ROLE.ADMIN, ROLE.DIRETORIA, ROLE.RH, ROLE.MANUTENCAO_SUPERVISOR, ROLE.SUPERVISOR_MANUTENCAO, ROLE.ENCARREGADO_MANUTENCAO, ROLE.MECANICO],
  inspecao_view: [
    ROLE.INSPECAO_QUALIDADE,
    ROLE.ADMIN,
    ROLE.MANUTENCAO_SUPERVISOR,
    ROLE.MECANICO,
    ROLE.DIRETORIA,
    ROLE.COMPRAS,
    ROLE.ALMOXARIFADO,
    ROLE.RH,
  ],
  inspecao_edit: [ROLE.INSPECAO_QUALIDADE, ROLE.ADMIN, ROLE.MANUTENCAO_SUPERVISOR],
  tracagem_view: [
    ROLE.ADMIN,
    ROLE.MANUTENCAO_SUPERVISOR,
    ROLE.ENCARREGADO_MANUTENCAO,
    ROLE.MECANICO,
    ROLE.GESTAO,
    ROLE.COMPRAS,
    ROLE.ALMOXARIFADO,
  ],
  tracagem_manage: [ROLE.ADMIN, ROLE.MANUTENCAO_SUPERVISOR, ROLE.ENCARREGADO_MANUTENCAO],
  desenho_tecnico_view: [
    ROLE.ADMIN,
    ROLE.MANUTENCAO_SUPERVISOR,
    ROLE.ENCARREGADO_MANUTENCAO,
    ROLE.MECANICO,
    ROLE.DIRETORIA,
    ROLE.COMPRAS,
    ROLE.ALMOXARIFADO,
  ],
  desenho_tecnico_manage: [ROLE.ADMIN, ROLE.MANUTENCAO_SUPERVISOR, ROLE.ENCARREGADO_MANUTENCAO, ROLE.MECANICO],
  academia_view: [ROLE.ADMIN, ROLE.MANUTENCAO_SUPERVISOR, ROLE.MECANICO],
  academia_manage: [ROLE.ADMIN, ROLE.MANUTENCAO_SUPERVISOR],
  colaboradores: [ROLE.ADMIN, ROLE.RH, ROLE.ENCARREGADO_MANUTENCAO, ROLE.MANUTENCAO_SUPERVISOR, ROLE.COLABORADOR],

  equipamentos_delete: [ROLE.ADMIN],
  os_delete: [ROLE.ADMIN],
  preventivas_delete: [ROLE.ADMIN],
  demandas_delete: [ROLE.ADMIN],
  solicitacoes_delete: [ROLE.ADMIN],
  compras_delete: [ROLE.ADMIN],
  fornecedores_delete: [ROLE.ADMIN],
  almoxarifado_delete: [ROLE.ADMIN],
  estoque_delete: [ROLE.ADMIN],
  motores_delete: [ROLE.ADMIN],
  avisos_delete: [ROLE.ADMIN],
  escala_delete: [ROLE.ADMIN],
  inspecao_delete: [ROLE.ADMIN],
  tracagem_delete: [ROLE.ADMIN],
  desenho_tecnico_delete: [ROLE.ADMIN],
  pcm_delete: [ROLE.ADMIN],
  usuarios_delete: [ROLE.ADMIN],
  arquivos_delete: [ROLE.ADMIN],
  anexos_delete: [ROLE.ADMIN],
};

function canAccessModule(role, moduleKey) {
  const n = normalizeRole(role);
  if (n === ROLE.ADMIN) return true;
  const allowed = ACCESS[moduleKey] || [];
  return allowed.includes(n);
}

module.exports = { ROLE, ACCESS, normalizeRole, canAccessModule };
