const ROLE = {
  ADMIN: 'ADMIN',
  DIRETORIA: 'DIRETORIA',
  RH: 'RH',
  ENCARREGADO_PRODUCAO: 'ENCARREGADO_PRODUCAO',
  PRODUCAO: 'PRODUCAO',
  MECANICO: 'MECANICO',
  ALMOXARIFADO: 'ALMOXARIFADO',
  COMPRAS: 'COMPRAS',
  MANUTENCAO_SUPERVISOR: 'MANUTENCAO_SUPERVISOR',
  COORDENADOR_RECICLAGEM: 'COORDENADOR_RECICLAGEM',
  SUPERVISOR_MANUTENCAO: 'SUPERVISOR_MANUTENCAO',
  ENCARREGADO_MANUTENCAO: 'ENCARREGADO_MANUTENCAO',
  ENCARREGADO_LOGISTICA: 'ENCARREGADO_LOGISTICA',
  ENCARREGADO_FRIGORIFICO: 'ENCARREGADO_FRIGORIFICO',
  GESTAO: 'GESTAO',
  PCM: 'PCM',
  COLABORADOR: 'COLABORADOR',
  INSPECAO_QUALIDADE: 'INSPECAO_QUALIDADE',
};

function normalizeRole(role) {
  const r = String(role || '')
    .trim()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toUpperCase()
    .replace(/[\s-]+/g, '_');
  if (r === 'ADMINISTRADOR') return ROLE.ADMIN;
  if (r === 'DIRECAO') return ROLE.DIRETORIA;
  if (r === 'ALMOXARIFE') return ROLE.ALMOXARIFADO;
  if (r === 'MANUTENCAO') return ROLE.MANUTENCAO_SUPERVISOR;
  if (r === 'SUPERVISOR_MANUTENCAO') return ROLE.MANUTENCAO_SUPERVISOR;
  if (['COORDENADOR', 'COORDENADOR_RECICLAGEM', 'COORDENADOR_DA_RECICLAGEM'].includes(r)) return ROLE.COORDENADOR_RECICLAGEM;
  if (['ENCARREGADO', 'ENCARREGADO_MANUTENCAO', 'ENCARREGADO_DE_MANUTENCAO'].includes(r)) return ROLE.ENCARREGADO_MANUTENCAO;
  if (['INSPECAO_QUALIDADE', 'INSPECAO_E_QUALIDADE', 'QUALIDADE'].includes(r)) return ROLE.INSPECAO_QUALIDADE;
  return r;
}

const ACCESS = {
  dashboard_criticidade: [ROLE.ADMIN, ROLE.DIRETORIA, ROLE.PCM, ROLE.MANUTENCAO_SUPERVISOR, ROLE.ENCARREGADO_MANUTENCAO, ROLE.MECANICO, ROLE.COORDENADOR_RECICLAGEM],
  painel_operacional: [ROLE.INSPECAO_QUALIDADE, ROLE.ADMIN, ROLE.DIRETORIA, ROLE.RH, ROLE.ENCARREGADO_PRODUCAO, ROLE.PRODUCAO, ROLE.MECANICO, ROLE.MANUTENCAO_SUPERVISOR, ROLE.COORDENADOR_RECICLAGEM],

  // Painel da Diretoria: área executiva separada dos módulos operacionais.
  diretoria_dashboard: [ROLE.ADMIN, ROLE.DIRETORIA],
  diretoria_compras: [ROLE.ADMIN, ROLE.DIRETORIA, ROLE.COORDENADOR_RECICLAGEM],
  diretoria_manutencao: [ROLE.ADMIN, ROLE.DIRETORIA],

  // PCM operacional: Diretoria deixa de navegar por planejamento, engenharia,
  // lubrificação e demais telas técnicas. Seus indicadores ficam em /diretoria.
  pcm: [ROLE.ADMIN, ROLE.ENCARREGADO_MANUTENCAO],
  pcm_manage: [ROLE.ADMIN, ROLE.ENCARREGADO_MANUTENCAO],
  equipamentos: [ROLE.INSPECAO_QUALIDADE, ROLE.ADMIN, ROLE.DIRETORIA, ROLE.MECANICO, ROLE.MANUTENCAO_SUPERVISOR, ROLE.COORDENADOR_RECICLAGEM],
  equipamentos_manage: [ROLE.ADMIN, ROLE.MECANICO, ROLE.MANUTENCAO_SUPERVISOR],
  os_view: [ROLE.INSPECAO_QUALIDADE, ROLE.ADMIN, ROLE.DIRETORIA, ROLE.RH, ROLE.ENCARREGADO_PRODUCAO, ROLE.PRODUCAO, ROLE.MECANICO, ROLE.MANUTENCAO_SUPERVISOR, ROLE.COORDENADOR_RECICLAGEM],
  os_open: [ROLE.INSPECAO_QUALIDADE, ROLE.ADMIN, ROLE.DIRETORIA, ROLE.ENCARREGADO_PRODUCAO, ROLE.PRODUCAO, ROLE.MECANICO, ROLE.MANUTENCAO_SUPERVISOR, ROLE.COORDENADOR_RECICLAGEM],
  os_execute: [ROLE.ADMIN, ROLE.MECANICO, ROLE.MANUTENCAO_SUPERVISOR],
  os_chat_read: [ROLE.ADMIN, ROLE.MANUTENCAO_SUPERVISOR, ROLE.ENCARREGADO_MANUTENCAO, ROLE.MECANICO, ROLE.COMPRAS, ROLE.INSPECAO_QUALIDADE, ROLE.DIRETORIA, ROLE.ALMOXARIFADO, ROLE.COORDENADOR_RECICLAGEM],
  os_chat_write: [ROLE.ADMIN, ROLE.MANUTENCAO_SUPERVISOR, ROLE.ENCARREGADO_MANUTENCAO, ROLE.MECANICO, ROLE.COMPRAS, ROLE.INSPECAO_QUALIDADE, ROLE.ALMOXARIFADO, ROLE.COORDENADOR_RECICLAGEM],
  os_chat_manage: [ROLE.ADMIN, ROLE.MANUTENCAO_SUPERVISOR, ROLE.ENCARREGADO_MANUTENCAO],
  assistente_manutencao: [ROLE.ADMIN, ROLE.DIRETORIA, ROLE.COMPRAS, ROLE.MANUTENCAO_SUPERVISOR, ROLE.ENCARREGADO_MANUTENCAO, ROLE.MECANICO, ROLE.COORDENADOR_RECICLAGEM],
  // Regra operacional: quem acessa o painel operacional também enxerga Preventivas.
  preventivas_view: [ROLE.INSPECAO_QUALIDADE, ROLE.ADMIN, ROLE.DIRETORIA, ROLE.RH, ROLE.ENCARREGADO_PRODUCAO, ROLE.MECANICO, ROLE.MANUTENCAO_SUPERVISOR, ROLE.COORDENADOR_RECICLAGEM],
  preventivas_manage: [ROLE.ADMIN, ROLE.ENCARREGADO_MANUTENCAO],
  preventivas_execute: [ROLE.ADMIN, ROLE.MECANICO, ROLE.MANUTENCAO_SUPERVISOR],
  // Execução operacional do plano: planejamento permanece no PCM; mecânico apenas executa o roteiro distribuído.
  lubrificacao_execucao: [ROLE.MECANICO],
  demandas_view: [ROLE.INSPECAO_QUALIDADE, ROLE.ADMIN, ROLE.DIRETORIA, ROLE.GESTAO, ROLE.RH, ROLE.ENCARREGADO_PRODUCAO, ROLE.MANUTENCAO_SUPERVISOR, ROLE.ENCARREGADO_MANUTENCAO, ROLE.COMPRAS, ROLE.COORDENADOR_RECICLAGEM],
  demandas_open: [ROLE.INSPECAO_QUALIDADE, ROLE.ADMIN, ROLE.DIRETORIA, ROLE.GESTAO, ROLE.RH, ROLE.ENCARREGADO_PRODUCAO, ROLE.MANUTENCAO_SUPERVISOR, ROLE.ENCARREGADO_MANUTENCAO, ROLE.COORDENADOR_RECICLAGEM],
  demandas_manage: [ROLE.ADMIN, ROLE.DIRETORIA, ROLE.MANUTENCAO_SUPERVISOR, ROLE.ENCARREGADO_MANUTENCAO, ROLE.COORDENADOR_RECICLAGEM],
  demandas_materials: [ROLE.ADMIN, ROLE.MANUTENCAO_SUPERVISOR, ROLE.ENCARREGADO_MANUTENCAO, ROLE.COORDENADOR_RECICLAGEM],
  demandas_convert: [ROLE.ADMIN, ROLE.MANUTENCAO_SUPERVISOR, ROLE.ENCARREGADO_MANUTENCAO, ROLE.COORDENADOR_RECICLAGEM],
  demandas_approve: [ROLE.ADMIN, ROLE.DIRETORIA, ROLE.GESTAO],

  compras_read: [ROLE.ADMIN, ROLE.COMPRAS, ROLE.DIRETORIA, ROLE.GESTAO, ROLE.PCM, ROLE.MANUTENCAO_SUPERVISOR, ROLE.ENCARREGADO_MANUTENCAO],
  compras_manage: [ROLE.ADMIN, ROLE.COMPRAS],
  // Coordenador da Reciclagem opera somente registros do próprio setor.
  // As rotas que usam estas chaves DEVEM aplicar o guard de escopo da Reciclagem.
  compras_reciclagem_read: [ROLE.COORDENADOR_RECICLAGEM],
  compras_reciclagem_manage: [ROLE.COORDENADOR_RECICLAGEM],
  solicitacoes_reciclagem_read: [ROLE.COORDENADOR_RECICLAGEM],
  solicitacoes_reciclagem_create: [ROLE.COORDENADOR_RECICLAGEM],
  solicitacoes_reciclagem_manage: [ROLE.COORDENADOR_RECICLAGEM],
  solicitacoes_reciclagem_delete: [ROLE.COORDENADOR_RECICLAGEM],
  // Acompanhamento gerencial: consulta por setor, sem ações de compra/recebimento.
  acompanhamento_compras: [ROLE.ADMIN, ROLE.RH, ROLE.MANUTENCAO_SUPERVISOR, ROLE.ENCARREGADO_MANUTENCAO, ROLE.ENCARREGADO_LOGISTICA, ROLE.ENCARREGADO_FRIGORIFICO],
  solicitacoes_read: [ROLE.INSPECAO_QUALIDADE, ROLE.ADMIN, ROLE.DIRETORIA, ROLE.COMPRAS, ROLE.ALMOXARIFADO, ROLE.RH, ROLE.ENCARREGADO_PRODUCAO, ROLE.ENCARREGADO_MANUTENCAO, ROLE.MANUTENCAO_SUPERVISOR, ROLE.ENCARREGADO_LOGISTICA, ROLE.ENCARREGADO_FRIGORIFICO, ROLE.COORDENADOR_RECICLAGEM],
  solicitacoes_create: [ROLE.INSPECAO_QUALIDADE, ROLE.ADMIN, ROLE.RH, ROLE.ENCARREGADO_PRODUCAO, ROLE.ENCARREGADO_MANUTENCAO, ROLE.MANUTENCAO_SUPERVISOR, ROLE.ENCARREGADO_LOGISTICA, ROLE.ENCARREGADO_FRIGORIFICO, ROLE.DIRETORIA, ROLE.COORDENADOR_RECICLAGEM],
  solicitacoes_manage: [ROLE.ADMIN, ROLE.RH, ROLE.ENCARREGADO_MANUTENCAO, ROLE.MANUTENCAO_SUPERVISOR, ROLE.ENCARREGADO_LOGISTICA, ROLE.ENCARREGADO_FRIGORIFICO, ROLE.COORDENADOR_RECICLAGEM],

  // Pré-solicitação semanal do Almoxarifado: criação separada da solicitação
  // comum e aprovação restrita ao responsável do setor.
  pre_solicitacao_almox_read: [ROLE.ADMIN, ROLE.ALMOXARIFADO, ROLE.RH, ROLE.ENCARREGADO_MANUTENCAO, ROLE.MANUTENCAO_SUPERVISOR, ROLE.ENCARREGADO_LOGISTICA, ROLE.ENCARREGADO_FRIGORIFICO],
  pre_solicitacao_almox_create: [ROLE.ADMIN, ROLE.ALMOXARIFADO],
  pre_solicitacao_setor_approve: [ROLE.ADMIN, ROLE.RH, ROLE.ENCARREGADO_MANUTENCAO, ROLE.MANUTENCAO_SUPERVISOR, ROLE.ENCARREGADO_LOGISTICA, ROLE.ENCARREGADO_FRIGORIFICO],

  almoxarifado_read: [ROLE.ADMIN, ROLE.ALMOXARIFADO, ROLE.DIRETORIA],
  almoxarifado_manage: [ROLE.ADMIN, ROLE.ALMOXARIFADO],
  diretoria_aprovacao: [ROLE.ADMIN, ROLE.DIRETORIA, ROLE.GESTAO],
  notificacoes_view: [ROLE.INSPECAO_QUALIDADE, ROLE.ADMIN, ROLE.DIRETORIA, ROLE.COMPRAS, ROLE.ALMOXARIFADO, ROLE.RH, ROLE.ENCARREGADO_PRODUCAO, ROLE.ENCARREGADO_MANUTENCAO, ROLE.MANUTENCAO_SUPERVISOR, ROLE.ENCARREGADO_LOGISTICA, ROLE.ENCARREGADO_FRIGORIFICO, ROLE.COORDENADOR_RECICLAGEM],
  avisos_view: [ROLE.ADMIN, ROLE.DIRETORIA, ROLE.RH, ROLE.ENCARREGADO_PRODUCAO, ROLE.MANUTENCAO_SUPERVISOR, ROLE.COORDENADOR_RECICLAGEM],
  avisos_manage: [ROLE.ADMIN, ROLE.DIRETORIA, ROLE.RH, ROLE.ENCARREGADO_PRODUCAO, ROLE.MANUTENCAO_SUPERVISOR],
  estoque_manage: [ROLE.ADMIN, ROLE.ALMOXARIFADO],
  estoque_retirada: [ROLE.ADMIN, ROLE.ALMOXARIFADO, ROLE.MECANICO, ROLE.MANUTENCAO_SUPERVISOR, ROLE.ENCARREGADO_MANUTENCAO],
  estoque_view: [ROLE.ADMIN, ROLE.ALMOXARIFADO, ROLE.COMPRAS],
  motores: [ROLE.ADMIN, ROLE.ALMOXARIFADO, ROLE.MANUTENCAO_SUPERVISOR, ROLE.COORDENADOR_RECICLAGEM],
  compras: [ROLE.ADMIN, ROLE.COMPRAS],
  fornecedores: [ROLE.ADMIN, ROLE.COMPRAS, ROLE.GESTAO, ROLE.DIRETORIA, ROLE.PCM],
  fornecedores_manage: [ROLE.ADMIN, ROLE.COMPRAS],
  usuarios: [ROLE.ADMIN],

  // Escala: a visão geral continua restrita. O autoatendimento é pessoal e
  // fica disponível a todos os perfis autenticados que possuam ficha vinculada.
  escala: [ROLE.ADMIN, ROLE.DIRETORIA, ROLE.RH, ROLE.MANUTENCAO_SUPERVISOR, ROLE.SUPERVISOR_MANUTENCAO, ROLE.ENCARREGADO_MANUTENCAO, ROLE.MECANICO, ROLE.COORDENADOR_RECICLAGEM],
  escala_self: [ROLE.ADMIN, ROLE.DIRETORIA, ROLE.RH, ROLE.ENCARREGADO_PRODUCAO, ROLE.PRODUCAO, ROLE.MECANICO, ROLE.ALMOXARIFADO, ROLE.COMPRAS, ROLE.MANUTENCAO_SUPERVISOR, ROLE.SUPERVISOR_MANUTENCAO, ROLE.ENCARREGADO_MANUTENCAO, ROLE.GESTAO, ROLE.PCM, ROLE.COLABORADOR, ROLE.INSPECAO_QUALIDADE, ROLE.COORDENADOR_RECICLAGEM],
  escala_rh: [ROLE.ADMIN, ROLE.RH, ROLE.DIRETORIA],
  escala_manage: [ROLE.ADMIN, ROLE.MANUTENCAO_SUPERVISOR, ROLE.SUPERVISOR_MANUTENCAO, ROLE.ENCARREGADO_MANUTENCAO],
  escala_reports: [ROLE.ADMIN, ROLE.RH, ROLE.DIRETORIA, ROLE.MANUTENCAO_SUPERVISOR, ROLE.SUPERVISOR_MANUTENCAO, ROLE.ENCARREGADO_MANUTENCAO, ROLE.MECANICO, ROLE.COORDENADOR_RECICLAGEM],

  // RH integrado: Diretoria consulta visão geral; dados e anexos sensíveis
  // permanecem restritos a RH/ADMIN. A aprovação operacional de folgas continua
  // em escala_manage e não é ampliada por estas permissões.
  rh_view: [ROLE.ADMIN, ROLE.RH, ROLE.DIRETORIA],
  rh_manage: [ROLE.ADMIN, ROLE.RH],
  rh_sensitive: [ROLE.ADMIN, ROLE.RH],

  inspecao_view: [
    ROLE.INSPECAO_QUALIDADE,
    ROLE.ADMIN,
    ROLE.MANUTENCAO_SUPERVISOR,
    ROLE.MECANICO,
    ROLE.DIRETORIA,
    ROLE.ALMOXARIFADO,
    ROLE.RH,
    ROLE.COORDENADOR_RECICLAGEM,
  ],
  inspecao_edit: [ROLE.INSPECAO_QUALIDADE, ROLE.ADMIN, ROLE.MANUTENCAO_SUPERVISOR],
  tracagem_view: [
    ROLE.ADMIN,
    ROLE.MANUTENCAO_SUPERVISOR,
    ROLE.ENCARREGADO_MANUTENCAO,
    ROLE.MECANICO,
    ROLE.GESTAO,
    ROLE.ALMOXARIFADO,
    ROLE.COORDENADOR_RECICLAGEM,
  ],
  tracagem_manage: [ROLE.ADMIN, ROLE.MANUTENCAO_SUPERVISOR, ROLE.ENCARREGADO_MANUTENCAO],
  desenho_tecnico_view: [
    ROLE.ADMIN,
    ROLE.MANUTENCAO_SUPERVISOR,
    ROLE.ENCARREGADO_MANUTENCAO,
    ROLE.MECANICO,
    ROLE.ALMOXARIFADO,
    ROLE.COORDENADOR_RECICLAGEM,
  ],
  desenho_tecnico_manage: [ROLE.ADMIN, ROLE.MANUTENCAO_SUPERVISOR, ROLE.ENCARREGADO_MANUTENCAO, ROLE.MECANICO],
  academia_view: [ROLE.ADMIN, ROLE.MANUTENCAO_SUPERVISOR, ROLE.MECANICO, ROLE.COORDENADOR_RECICLAGEM],
  academia_manage: [ROLE.ADMIN, ROLE.MANUTENCAO_SUPERVISOR],
  colaboradores: [ROLE.ADMIN, ROLE.RH, ROLE.ENCARREGADO_MANUTENCAO, ROLE.MANUTENCAO_SUPERVISOR, ROLE.COLABORADOR],

  equipamentos_delete: [ROLE.ADMIN],
  os_delete: [ROLE.ADMIN],
  preventivas_delete: [ROLE.ADMIN],
  demandas_delete: [ROLE.ADMIN],
  solicitacoes_delete: [ROLE.ADMIN],
  compras_delete: [ROLE.ADMIN],
  fornecedores_delete: [ROLE.ADMIN],
  almoxarifado_delete: [ROLE.ADMIN],
  estoque_delete: [ROLE.ADMIN],
  motores_delete: [ROLE.ADMIN],
  avisos_delete: [ROLE.ADMIN],
  escala_delete: [ROLE.ADMIN],
  inspecao_delete: [ROLE.ADMIN],
  tracagem_delete: [ROLE.ADMIN],
  desenho_tecnico_delete: [ROLE.ADMIN],
  pcm_delete: [ROLE.ADMIN],
  usuarios_delete: [ROLE.ADMIN],
  arquivos_delete: [ROLE.ADMIN],
  anexos_delete: [ROLE.ADMIN],
};

function canAccessModule(role, moduleKey) {
  const n = normalizeRole(role);
  if (n === ROLE.ADMIN) return true;
  const allowed = ACCESS[moduleKey] || [];
  return allowed.includes(n);
}

module.exports = { ROLE, ACCESS, normalizeRole, canAccessModule };
