const express=require('express');const router=express.Router();
const {requireLogin,requireRole}=require('../auth/auth.middleware');const {ACCESS}=require('../../config/rbac');const ctrl=require('./fornecedores.controller');
const read=ACCESS.fornecedores;const manage=ACCESS.fornecedores_manage;
router.get('/',requireLogin,requireRole(read),ctrl.list);
router.get('/api/pesquisa',requireLogin,requireRole(ACCESS.compras_read),ctrl.api);
router.get('/novo',requireLogin,requireRole(manage),ctrl.newForm);
router.post('/',requireLogin,requireRole(manage),ctrl.create);
router.get('/:id/editar',requireLogin,requireRole(manage),ctrl.editForm);
router.post('/:id',requireLogin,requireRole(manage),ctrl.update);
router.post('/:id/:action(favorito|situacao)',requireLogin,requireRole(manage),ctrl.toggle);
router.get('/:id',requireLogin,requireRole(read),ctrl.profile);
module.exports=router;
